###
POST http://localhost:3000/login
Content-Type: application/json

{
    "senha": "Teste1",
    "email": "marcosa@gmail.com"
}

###
GET http://localhost:3000/usuarios

###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "senha": "Teste1",
    "email": "marcosa@gmail.com"
}

###
PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
    "email": "marLonbrando@gmail.com",
    "senha": "12345"
}

###
DELETE http://localhost:3000/usuarios/1

###
GET http://localhost:3000/usuarios/1/arquivos

###

POST http://localhost:3000/arquivos
Content-Type: application/json

{
    "Nome": "Teste",
    "LingProg": "Python"
}

###

PUT http://localhost:3000/arquivos/1
Content-Type: application/json

{
    "Nome": "Teste2",
    "LingProg": "JavaScript"
}


###

DELETE http://localhost:3000/arquivos/1